service: mozilla-session-invalidation
provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:ListBuckets
        - s3:GetObject
      Resource:
        - Fn::GetAtt:
           - StaticContentBucket
           - Arn
#    - Effect: Allow
#      Action:
#        - sqs:SendMessage
#      Resource: !GetAtt SQSToMozDef.Arn
  Outputs:
    StaticContentBucket:
      Description: The URL of the S3 bucket used to host static content
      Value:
        Fn::GetAtt
          - StaticContentBucket
          - WebsiteURL
resources:
  Resources:
    StaticContentBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: session-invalidation-static-content
        AccessControl: Private
#    SQSToMozDef:
#      Type: AWS::SQS::Queue
#      Properties:
#        MessageRetentionPeriod: 345600  # 4 days, the AWS default
#        Tags:
#          - Key: application
#            Value: session-invalidation
#          - Key: stack
#            Value: !Ref AWS::StackName
#          - Key: source
#            Value: https://github.com/mozilla/session-invalidation
package:
  include:
#    - mozilla_session_invalidation/**
    - lib/**
functions:
  index:
    handler: lambda.index
    events:
      - http: get /
  terminate:
    handler: lambda.terminate
    events:
      - http: post /terminate
