service: mozilla-session-invalidation
provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:ListBuckets
        - s3:GetObject
      Resource: !Ref StaticContentBucket.Arn
#    - Effect: Allow
#      Action:
#        - sqs:SendMessage
#      Resource: !GetAtt SQSToMozDef.Arn
  Resources:
    StaticContentBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: SessionInvalidationStaticContent
        AccessControl: Private
#    SQSToMozDef:
#      Type: AWS::SQS::Queue
#      Properties:
#        MessageRetentionPeriod: 345600  # 4 days, the AWS default
#        Tags:
#          - Key: application
#            Value: session-invalidation
#          - Key: stack
#            Value: !Ref AWS::StackName
#          - Key: source
#            Value: https://github.com/mozilla/session-invalidation
#package:
#  include:
#    - mozilla_session_invalidation/**
functions:
  index:
    handler: lambda.index
    events:
      - http: get /
  terminate:
    handler: lambda.terminate
    events:
      - http: post /terminate
